4 th week my operating system creation, I have those errors, I need to find solutions.
gcc -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -Wall -Wextra -Werror -c  kmain.c -o kmain.o
In file included from kmain.c:1:
frame_buffer.h: In function ‘fb_write_cell’:
frame_buffer.h:54:3: error: ‘fb’ undeclared (first use in this function); did you mean ‘fg’?
   54 |   fb[i] = c;
      |   ^~
      |   fg
frame_buffer.h:54:3: note: each undeclared identifier is reported only once for each function it appears in
frame_buffer.h:55:44: error: expected ‘)’ before ‘;’ token
   55 |   fb[i+1] = ((fg & 0x0F) << 4 | (bg & 0x0F);
      |             ~                              ^
      |                                            )
frame_buffer.h:55:45: error: expected ‘;’ before ‘}’ token
   55 |   fb[i+1] = ((fg & 0x0F) << 4 | (bg & 0x0F);
      |                                             ^
      |                                             ;
   56 |  }
      |  ~                                           
frame_buffer.h: In function ‘fb_write’:
frame_buffer.h:68:19: error: ‘writing_state’ undeclared (first use in this function)
   68 |    fb_write_cell((writing_state+(i*2)), *(buf+i), FB_GREEN, FB_DARK_GREY);
      |                   ^~~~~~~~~~~~~
frame_buffer.h:71:3: error: ‘cursor_state’ undeclared (first use in this function)
   71 |   cursor_state+=len;
      |   ^~~~~~~~~~~~
In file included from kmain.c:2:
serial_port.h: At top level:
serial_port.h:41:8: error: redeclaration of ‘enum BaudRate’
   41 |   enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |        ^~~~~~~~
serial_port.h:23:6: note: originally defined here
   23 | enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |      ^~~~~~~~
serial_port.h:41:19: error: redeclaration of enumerator ‘Baud_115200’
   41 |   enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                   ^~~~~~~~~~~
serial_port.h:23:17: note: previous definition of ‘Baud_115200’ was here
   23 | enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                 ^~~~~~~~~~~
serial_port.h:41:36: error: redeclaration of enumerator ‘Baud_57600’
   41 |   enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                                    ^~~~~~~~~~
serial_port.h:23:34: note: previous definition of ‘Baud_57600’ was here
   23 | enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                                  ^~~~~~~~~~
serial_port.h:41:48: error: redeclaration of enumerator ‘Baud_19200’
   41 |   enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                                                ^~~~~~~~~~
serial_port.h:23:46: note: previous definition of ‘Baud_19200’ was here
   23 | enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                                              ^~~~~~~~~~
serial_port.h:41:60: error: redeclaration of enumerator ‘Baud_9600’
   41 | enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                                                          ^~~~~~~~~

serial_port.h:23:58: note: previous definition of ‘Baud_9600’ was here
   23 | enum BaudRate { Baud_115200 = 1, Baud_57600, Baud_19200, Baud_9600 };
      |                                                          ^~~~~~~~~
serial_port.h: In function ‘serial_write’:
serial_port.h:115:7: error: implicit declaration of function ‘serial_configure’; did you mean ‘serial_configure_line’? [-Werror=implicit-function-declaration]
  115 |       serial_configure(com , divisor);
      |       ^~~~~~~~~~~~~~~~
      |       serial_configure_line
serial_port.h:119:12: error: implicit declaration of function ‘serial_write_byte’; did you mean ‘serial_write’? [-Werror=implicit-function-declaration]
  119 |            serial_write_byte(com, buf[indexToBuffer]);
      |            ^~~~~~~~~~~~~~~~~
      |            serial_write
serial_port.h: At top level:
serial_port.h:132:6: error: conflicting types for ‘serial_write_byte’ [-Werror]
  132 | void serial_write_byte(unsigned short port, char byteData)
      |      ^~~~~~~~~~~~~~~~~
serial_port.h:119:12: note: previous implicit declaration of ‘serial_write_byte’ was here
  119 |            serial_write_byte(com, buf[indexToBuffer]);
      |            ^~~~~~~~~~~~~~~~~
serial_port.h:143:6: error: conflicting types for ‘serial_configure’ [-Werror]
  143 | void serial_configure(unsigned short port, unsigned short baudRate)
      |      ^~~~~~~~~~~~~~~~
serial_port.h:115:7: note: previous implicit declaration of ‘serial_configure’ was here
  115 |       serial_configure(com , divisor);
      |       ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:31: kmain.o] Error 1